# Generated by Django 4.2.27 on 2026-09-16 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career_app', '0003_notification_savedjob_viewedrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Resume', max_length=200)),
                ('template_name', models.CharField(default='modern', max_length=50)),
                ('theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='career_app__user_id_424585_idx')],
            },
        ),
    ]
